name: simple_statistical_calculator
description: "My first app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  lottie: ^3.0.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  flutter_gen: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/interfonts/
    - assets/fonts/vazirfonts/
    - assets/images/
    - assets/jsonimages/
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/vazirfonts/Vazirmatn-Thin.ttf
          weight: 100
        - asset: assets/fonts/vazirfonts/Vazirmatn-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/vazirfonts/Vazirmatn-Light.ttf
          weight: 300
        - asset: assets/fonts/vazirfonts/Vazirmatn-Regular.ttf
          weight: 400
        - asset: assets/fonts/vazirfonts/Vazirmatn-Medium.ttf
          weight: 500
        - asset: assets/fonts/vazirfonts/Vazirmatn-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/vazirfonts/Vazirmatn-Bold.ttf
          weight: 700
        - asset: assets/fonts/vazirfonts/Vazirmatn-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/vazirfonts/Vazirmatn-Black.ttf
          weight: 900
    - family: Inter
      fonts:
        - asset: assets/fonts/interfonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/interfonts/Inter-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/interfonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/interfonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/interfonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/interfonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/interfonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/interfonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/interfonts/Inter-Black.ttf
          weight: 900
